name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           submodules: true
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git submodule foreach --recursive git checkout master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Build site
        run: bundle exec appraisal jekyll build --future
