name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           submodules: true
      - name: Update submodules
        run: |
         git submodule update --remote --recursive
         git submodule foreach --recursive git checkout master

      - name: Commit and push if changes are present
        run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
         git commit -am "Automatically update submodules" || echo "No changes to commit"
         git push origin HEAD:main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Build site
        run: bundle exec appraisal jekyll build --future
